 -- create database PROYECTO_CAFE;
use PROYECTO_CAFE;
CREATE TABLE TBL_OPERARIO (
    CEDULA_OPERARIO VARCHAR(20) NOT NULL,
    NOMBRE_OPERARIO VARCHAR(30) NOT NULL,
    TELEFONO_OPERARIO VARCHAR(30) NOT NULL,
    DIRECCION_OPERARIO VARCHAR(30) NOT NULL,
    EMAIL_OPERARIO VARCHAR(30) NOT NULL,
    FOTO_OPERARIO TEXT,
    PRIMARY KEY (CEDULA_OPERARIO),
    CONSTRAINT UNQ_CEDULA_OPERARIO UNIQUE (CEDULA_OPERARIO)
);

CREATE TABLE TBL_PROVEEDOR (
    CEDULA_PROVEEDOR VARCHAR(20) NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR(30) NOT NULL,
    TELEFONO_PROVEEDOR VARCHAR(30) NOT NULL,
    DIRECCION_PROVEEDOR VARCHAR(30) NOT NULL,
    EMAIL_PROVEEDOR VARCHAR(30) NOT NULL,
    FOTO_PROVEEDOR TEXT,
    PRIMARY KEY (CEDULA_PROVEEDOR),
    CONSTRAINT UNQ_CEDULA_PROVEEDOR UNIQUE (CEDULA_PROVEEDOR)
);

CREATE TABLE TBL_TIPO_PROCESO(
ID_TIPO_PROCESO INT AUTO_INCREMENT,
NOMBRE VARCHAR(30) NOT NULL,
 PRIMARY KEY (ID_TIPO_PROCESO)
);

CREATE TABLE TBL_VARIEDAD_CAFE(
ID_VARIEDAD_CAFE INT AUTO_INCREMENT,
NOMBRE VARCHAR(30) NOT NULL,
 PRIMARY KEY (ID_VARIEDAD_CAFE)
);

CREATE TABLE TBL_MAQUINA(
ID_MAQUINA VARCHAR (5) NOT NULL,
NOMBRE VARCHAR(20),
 PRIMARY KEY (ID_MAQUINA )
);

CREATE TABLE TBL_LOTE_CAFE (
    ID_LOTE_CAFE INT AUTO_INCREMENT,
    PESO VARCHAR(30) NOT NULL,
    CEDULA_PROVEEDOR VARCHAR(20),
    ID_TIPO_PROCESO INTEGER,
    ID_VARIEDAD_CAFE INTEGER,
    PRIMARY KEY (ID_LOTE_CAFE),
    CONSTRAINT FK_CEDULA_PROVEEDOR FOREIGN KEY (CEDULA_PROVEEDOR) REFERENCES TBL_PROVEEDOR (CEDULA_PROVEEDOR) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ID_TIPO_PROCESO FOREIGN KEY (ID_TIPO_PROCESO) REFERENCES TBL_TIPO_PROCESO (ID_TIPO_PROCESO) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ID_VARIEDAD_CAFE FOREIGN KEY (ID_VARIEDAD_CAFE) REFERENCES TBL_VARIEDAD_CAFE (ID_VARIEDAD_CAFE) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TBL_SEGUIMIENTO (
    ID_SEGUIMIENTO INT AUTO_INCREMENT,
    FECHA_HORA DATETIME,
    ID_LOTE_CAFE INTEGER,
    CEDULA_OPERARIO VARCHAR(20),
    PRIMARY KEY (ID_SEGUIMIENTO),
    CONSTRAINT FK_ID_LOTE_CAFE FOREIGN KEY (ID_LOTE_CAFE) REFERENCES TBL_LOTE_CAFE (ID_LOTE_CAFE) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CEDULA_OPERARIO FOREIGN KEY (CEDULA_OPERARIO) REFERENCES TBL_OPERARIO (CEDULA_OPERARIO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TBL_ESTADOS_MAQUINA (
    ID_ESTADOS_MAQUINA INT AUTO_INCREMENT,
    ESTADO VARCHAR(30) NOT NULL,
    ROTOR VARCHAR(32) UNIQUE NOT NULL,
    TEMPERATURA VARCHAR(30) NOT NULL,
    TEMPERATURA_S1 VARCHAR(30) NOT NULL,
    TEMPERATURA_S2 VARCHAR(30) NOT NULL,
    TEMPERATURA_PROMEDIO VARCHAR(30) NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    ID_MAQUINA VARCHAR(5),
    PRIMARY KEY (ID_ESTADOS_MAQUINA),
    CONSTRAINT FK_ID_MAQUINA FOREIGN KEY (ID_MAQUINA) REFERENCES TBL_MAQUINA (ID_MAQUINA) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TBL_RELACION_LOTE_ESTADO (
    ID_LOTE_CAFE INTEGER,
    ID_ESTADOS_MAQUINA INTEGER,
    PRIMARY KEY (ID_LOTE_CAFE, ID_ESTADOS_MAQUINA),
    CONSTRAINT FK_LOTE_CAFE_RELACION FOREIGN KEY (ID_LOTE_CAFE) REFERENCES TBL_LOTE_CAFE (ID_LOTE_CAFE) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_ESTADOS_MAQUINA_RELACION FOREIGN KEY (ID_ESTADOS_MAQUINA) REFERENCES TBL_ESTADOS_MAQUINA (ID_ESTADOS_MAQUINA) ON DELETE CASCADE ON UPDATE CASCADE
);
